collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3920759125612676
  brandStrength: 0.9928315
  lightness: 0.7595361606217921
  brandColors:
    - '#FEEA71'
    - '#354657'
    - '#EFA63F'
    - '#846550'
    - '#B5A49A'
  rhythmicContrast: 0.3137215143069625
typography_spectrum: 0.6900137786287814
layout_spectrum: 0.8924731
name: yicreative
author:
  name: Bren
  email: mark@yicreative.com
